package TEGApp;


/**
* TEGApp/baseI.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public interface baseI extends baseIOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface baseI
