package TEGApp;


/**
* TEGApp/PB.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public final class PB implements org.omg.CORBA.portable.IDLEntity
{
  public TEGApp.baseS infoR = null;
  public String methodName = null;
  public byte params[] = null;

  public PB ()
  {
  } // ctor

  public PB (TEGApp.baseS _infoR, String _methodName, byte[] _params)
  {
    infoR = _infoR;
    methodName = _methodName;
    params = _params;
  } // ctor

} // class PB
