package TEGApp;


/**
* TEGApp/C.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public interface C extends COperations, TEGApp.baseI, org.omg.CORBA.portable.IDLEntity 
{
} // interface C
