package TEGApp;


/**
* TEGApp/DOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public interface DOperations 
{
  void shutdown ();
  TEGApp.byt dataRequest (TEGApp.XD data);
  boolean dataInsert (TEGApp.XD data);
  boolean dataUpdate (TEGApp.XD data);
  void sendLog (TEGApp.XL data);
} // interface DOperations
