package TEGApp;

/**
* TEGApp/PHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public final class PHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.P value = null;

  public PHolder ()
  {
  }

  public PHolder (TEGApp.P initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.PHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.PHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.PHelper.type ();
  }

}
