package TEGApp;

/**
* TEGApp/XLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public final class XLHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.XL value = null;

  public XLHolder ()
  {
  }

  public XLHolder (TEGApp.XL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.XLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.XLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.XLHelper.type ();
  }

}
