package TEGApp;


/**
* TEGApp/baseS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public final class baseS implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String ipResponse = null;
  public String portResponse = null;

  public baseS ()
  {
  } // ctor

  public baseS (String _id, String _ipResponse, String _portResponse)
  {
    id = _id;
    ipResponse = _ipResponse;
    portResponse = _portResponse;
  } // ctor

} // class baseS
