package TEGApp;


/**
* TEGApp/SHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

abstract public class SHelper
{
  private static String  _id = "IDL:TEGApp/S:1.0";

  public static void insert (org.omg.CORBA.Any a, TEGApp.S that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TEGApp.S extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TEGApp.SHelper.id (), "S");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TEGApp.S read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TEGApp.S value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TEGApp.S narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TEGApp.S)
      return (TEGApp.S)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TEGApp._SStub stub = new TEGApp._SStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TEGApp.S unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TEGApp.S)
      return (TEGApp.S)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TEGApp._SStub stub = new TEGApp._SStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
