package TEGApp;


/**
* TEGApp/SPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

public abstract class SPOA extends org.omg.PortableServer.Servant
 implements TEGApp.SOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("senData", new java.lang.Integer (0));
    _methods.put ("updateConnections", new java.lang.Integer (1));
    _methods.put ("shutdown", new java.lang.Integer (2));
    _methods.put ("confirmation", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TEGApp/S/senData
       {
         TEGApp.CS data = TEGApp.CSHelper.read (in);
         TEGApp.XC $result = null;
         $result = this.senData (data);
         out = $rh.createReply();
         TEGApp.XCHelper.write (out, $result);
         break;
       }

       case 1:  // TEGApp/baseI/updateConnections
       {
         TEGApp.byt files = TEGApp.bytHelper.read (in);
         this.updateConnections (files);
         out = $rh.createReply();
         break;
       }

       case 2:  // TEGApp/baseI/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 3:  // TEGApp/baseI/confirmation
       {
         TEGApp.baseS data = TEGApp.baseSHelper.read (in);
         String objectName = in.read_string ();
         this.confirmation (data, objectName);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TEGApp/S:1.0", 
    "IDL:TEGApp/baseI:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public S _this() 
  {
    return SHelper.narrow(
    super._this_object());
  }

  public S _this(org.omg.CORBA.ORB orb) 
  {
    return SHelper.narrow(
    super._this_object(orb));
  }


} // class SPOA
