package TEGApp;

/**
* TEGApp/StoPHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public final class StoPHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.StoP value = null;

  public StoPHolder ()
  {
  }

  public StoPHolder (TEGApp.StoP initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.StoPHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.StoPHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.StoPHelper.type ();
  }

}
