package TEGApp;


/**
* TEGApp/THelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

abstract public class THelper
{
  private static String  _id = "IDL:TEGApp/T:1.0";

  public static void insert (org.omg.CORBA.Any a, TEGApp.T that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TEGApp.T extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TEGApp.THelper.id (), "T");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TEGApp.T read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TEGApp.T value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TEGApp.T narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TEGApp.T)
      return (TEGApp.T)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TEGApp._TStub stub = new TEGApp._TStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TEGApp.T unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TEGApp.T)
      return (TEGApp.T)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TEGApp._TStub stub = new TEGApp._TStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
