package TEGApp;

/**
* TEGApp/XCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:34 PM VET
*/

public final class XCHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.XC value = null;

  public XCHolder ()
  {
  }

  public XCHolder (TEGApp.XC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.XCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.XCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.XCHelper.type ();
  }

}
