package TEGApp;


/**
* TEGApp/XtoCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public interface XtoCOperations  extends TEGApp.baseIOperations
{
  void sendData (TEGApp.XC data);
} // interface XtoCOperations
