package TEGApp;

/**
* TEGApp/baseIHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

public final class baseIHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.baseI value = null;

  public baseIHolder ()
  {
  }

  public baseIHolder (TEGApp.baseI initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.baseIHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.baseIHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.baseIHelper.type ();
  }

}
