package TEGApp;


/**
* TEGApp/baseIOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

public interface baseIOperations 
{
  void updateConnections (TEGApp.byt files);
  void shutdown ();
  void confirmation (TEGApp.baseS data, String objectName);
} // interface baseIOperations
