package TEGApp;


/**
* TEGApp/byt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public final class byt implements org.omg.CORBA.portable.IDLEntity
{
  public byte obj[] = null;

  public byt ()
  {
  } // ctor

  public byt (byte[] _obj)
  {
    obj = _obj;
  } // ctor

} // class byt
