package TEGApp;


/**
* TEGApp/byt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:34 PM VET
*/

public final class byt implements org.omg.CORBA.portable.IDLEntity
{
  public byte obj[] = null;

  public byt ()
  {
  } // ctor

  public byt (byte[] _obj)
  {
    obj = _obj;
  } // ctor

} // class byt
