package TEGApp;

/**
* TEGApp/CHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public final class CHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.C value = null;

  public CHolder ()
  {
  }

  public CHolder (TEGApp.C initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.CHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.CHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.CHelper.type ();
  }

}
