package TEGApp;


/**
* TEGApp/SOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

public interface SOperations  extends TEGApp.baseIOperations
{
  TEGApp.XC senData (TEGApp.CS data);
} // interface SOperations
