package TEGApp;


/**
* TEGApp/TOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

public interface TOperations 
{
  TEGApp.byt getConnection (String objName, String host, String port);
} // interface TOperations
