package TEGApp;


/**
* TEGApp/DOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

public interface DOperations 
{
  void shutdown ();
  TEGApp.byt dataRequest (TEGApp.XD data);
  void sendLog (TEGApp.XL data);
} // interface DOperations
