package TEGApp;

/**
* TEGApp/PBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* miércoles 9 de enero de 2019 05:17:35 PM VET
*/

public final class PBHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.PB value = null;

  public PBHolder ()
  {
  }

  public PBHolder (TEGApp.PB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.PBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.PBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.PBHelper.type ();
  }

}
