package TEGApp;

/**
* TEGApp/PtoBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public final class PtoBHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.PtoB value = null;

  public PtoBHolder ()
  {
  }

  public PtoBHolder (TEGApp.PtoB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.PtoBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.PtoBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.PtoBHelper.type ();
  }

}
