package TEGApp;

/**
* TEGApp/XtoCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public final class XtoCHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.XtoC value = null;

  public XtoCHolder ()
  {
  }

  public XtoCHolder (TEGApp.XtoC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.XtoCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.XtoCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.XtoCHelper.type ();
  }

}
