package TEGApp;


/**
* TEGApp/CS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public final class CS implements org.omg.CORBA.portable.IDLEntity
{
  public TEGApp.baseS infoR = null;
  public int profile = (int)0;
  public String ObjectName = null;
  public String methodName = null;
  public String params[] = null;
  public String typeParams[] = null;

  public CS ()
  {
  } // ctor

  public CS (TEGApp.baseS _infoR, int _profile, String _ObjectName, String _methodName, String[] _params, String[] _typeParams)
  {
    infoR = _infoR;
    profile = _profile;
    ObjectName = _ObjectName;
    methodName = _methodName;
    params = _params;
    typeParams = _typeParams;
  } // ctor

} // class CS
