package TEGApp;

/**
* TEGApp/CtoSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

public final class CtoSHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.CtoS value = null;

  public CtoSHolder ()
  {
  }

  public CtoSHolder (TEGApp.CtoS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.CtoSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.CtoSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.CtoSHelper.type ();
  }

}
