package TEGApp;


/**
* TEGApp/StoPHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 14 de octubre de 2018 05:43:45 PM VET
*/

abstract public class StoPHelper
{
  private static String  _id = "IDL:TEGApp/StoP:1.0";

  public static void insert (org.omg.CORBA.Any a, TEGApp.StoP that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TEGApp.StoP extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TEGApp.StoPHelper.id (), "StoP");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TEGApp.StoP read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StoPStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TEGApp.StoP value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TEGApp.StoP narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TEGApp.StoP)
      return (TEGApp.StoP)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TEGApp._StoPStub stub = new TEGApp._StoPStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TEGApp.StoP unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TEGApp.StoP)
      return (TEGApp.StoP)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TEGApp._StoPStub stub = new TEGApp._StoPStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
