package TEGApp;

/**
* TEGApp/THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public final class THolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.T value = null;

  public THolder ()
  {
  }

  public THolder (TEGApp.T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.THelper.type ();
  }

}
