package TEGApp;


/**
* TEGApp/XC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* viernes 11 de enero de 2019 09:39:31 AM VET
*/

public final class XC implements org.omg.CORBA.portable.IDLEntity
{
  public String typeResponse = null;
  public byte Response[] = null;

  public XC ()
  {
  } // ctor

  public XC (String _typeResponse, byte[] _Response)
  {
    typeResponse = _typeResponse;
    Response = _Response;
  } // ctor

} // class XC
